In [1]:
a=100
b=100
c=a+b
print(c)

200


In [2]:
import numpy as np

In [3]:
import numpy as np

# Create a 1D Array (Vector)
vector = np.array([1, 2, 3, 4, 5])
print("1D Array:", vector) 

# Create a 2D Array (Matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", matrix)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:


arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

# Element-wise addition
print(arr1 + arr2)       # Output: [11 22 33]

# Scalar multiplication (multiplies every element by 2)
print(arr2 * 2)          


[11 22 33]
[2 4 6]


In [5]:
arr = np.array([12, 20, 1, 30, 40])
print(arr[3])
print(arr[arr>10])


30
[12 20 30 40]


In [7]:
arr = np.array([10, 24, 37, 57, 60])

print("Sum:",np.sum(arr))
print("Max:" ,np.max(arr))

print("Min:",np.min(arr))


Sum: 188
Max: 60
Min: 10


In [11]:
import pandas as pd

# Creating data
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}

# Converting dictionary to a Pandas DataFrame
df = pd.DataFrame(data)
print(df)


      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris


In [12]:
# View the first 2 rows of the DataFrame
print(df.head(2))

# Get summary statistics for numeric columns (mean, min, max, etc.)
print(df.describe())

# Check column names and data types
print(df.info())


    Name  Age      City
0  Alice   25  New York
1    Bob   30    London
        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None


In [13]:
# Select only the 'Age' column
print(df['Age'])

# Filter rows where Age is greater than 28
older_people = df[df['Age'] > 28]
print(older_people)


0    25
1    30
2    35
Name: Age, dtype: int64
      Name  Age    City
1      Bob   30  London
2  Charlie   35   Paris


In [14]:
import numpy as np

# Adding a missing value (NaN) for demonstration
df.loc[1, 'Age'] = np.nan 

# Check if there are any missing values
print(df.isnull().sum())

# Fill missing Ages with the average age
df['Age'] = df['Age'].fillna(df['Age'].mean())


Name    0
Age     1
City    0
dtype: int64


In [17]:
# Calculate the total sales for each Region/Category
sales_data = {
    'Region': ['North', 'North', 'South', 'South'],
    'Product': ['Apple', 'Orange', 'Apple', 'Orange'],
    'Sales': [100, 150, 200, 120]
}
sales_df = pd.DataFrame(sales_data)

# Group by Region and sum the sales
regional_sales = sales_df.groupby('Region')['Sales'].sum()
print(regional_sales)


Region
North    250
South    320
Name: Sales, dtype: int64
